### ISSUE TITLE
Flex-gap?

### ISSUE THREAD

**Issue by httpete** [bikk-uk/react-css-flex#41]
Flex-gap would be a great addition
https://coryrylan.com/blog/css-gap-space-with-flexbox

**Comment by httpete** [comment]
Delivered in:
https://github.com/bikk-uk/react-css-flex/pull/42
Please verify thank you.

**Comment by aboyce** [comment]
Hello, thanks for raising the issue and PR to fix this, agree it should be added. Will look to get the PR merged in and released out soon. Thanks 👍

**Comment by aboyce** [comment]
@httpete this should now be available in [v1.5.0](https://github.com/bikk-uk/react-css-flex/releases/tag/1.5.0), thanks 😀
